-- 코드를 입력하세요
SELECT DISTINCT CC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CR USING (CAR_ID)
WHERE CC.CAR_TYPE = '세단' AND CR.START_DATE BETWEEN "2022-10-01" AND "2022-10-31"
ORDER BY CC.CAR_ID DESC
